name: "[CI] Lint"

on:
  push:
  pull_request:

jobs:
  lint-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Recover Ruby dependency cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Install Ruby deps
        run: |
          gem install bundler:2.1.4
          bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Lint and Rubocop
        run: |
          bundle exec rubocop
          bundle exec erblint app/views/**/*.erb
